In [1]:
import numpy as np
x=np.array([1,2,3,4,5])
x

array([1, 2, 3, 4, 5])

In [2]:
print(type(x))

<class 'numpy.ndarray'>


In [ ]:
x=np.array(1,2,3,4,5)

In [3]:
x=np.array((1,2,3,4,5))

In [4]:
print(x)

[1 2 3 4 5]


In [5]:
x=np.array(4)
print(x)

4


In [6]:
x=np.array([[[1,2,3,4,],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(x)
print(x[0][1][2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
7


In [7]:
x.ndim

3

In [ ]:
x.ndim()

In [8]:
x=np.array([[[1,2,3,4,],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
print(x)
print(x[0,1,2])

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]
7


In [9]:
#generate array using arange function
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
x=np.arange(12)+1
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
x=np.arange(2,12)
print(x)
x=np.arange(2,12,3)
print(x)

[ 2  3  4  5  6  7  8  9 10 11]
[ 2  5  8 11]


In [12]:
x=np.arange(12,2)
print(x)

[]


In [13]:
x=np.arange(12,2,-1)
print(x)

[12 11 10  9  8  7  6  5  4  3]


In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
x=np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
x=x%2
print(x)

[[[1 0 1 0]
  [1 0 1 0]]

 [[1 0 1 0]
  [1 0 1 0]]]


In [17]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [18]:
np.zeros((5,4),dtype='int32')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [19]:
x=np.array([[10,20,30,40,50],[60,70,80,90,100]])
print(x[1,1:4])
print(x[:,2])
print(x[::-1,::-1])

[70 80 90]
[30 80]
[[100  90  80  70  60]
 [ 50  40  30  20  10]]


In [20]:
x+np.array([[2,3,7,3,7],[3,6,3,6,2]])

array([[ 12,  23,  37,  43,  57],
       [ 63,  76,  83,  96, 102]])

In [22]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [23]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [24]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [25]:
np.eye(6,4,-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [26]:
x=np.array([[1,2,3],[3,4,5]])
y=np.array([[1,2,3],[3,4,5]])
x*y

array([[ 1,  4,  9],
       [ 9, 16, 25]])

In [28]:
x=np.array([[1,2,3],[3,4,5]])
y=np.array([[1,2],[3,3],[4,5]])
x*y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [29]:
x.dtype

dtype('int32')

In [30]:
print(x)

[[1 2 3]
 [3 4 5]]


In [31]:
import numpy as np
x=np.array([[10,20,30,40,50],[60,70,80,90,100]])
x[0]=5
x

array([[  5,   5,   5,   5,   5],
       [ 60,  70,  80,  90, 100]])

In [36]:
import numpy as np
x=np.array([[10,20,40,50],[60,70,80,90,100]])
x

<ipython-input-36-804e841d73b2>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  x=np.array([[10,20,40,50],[60,70,80,90,100]])


array([list([10, 20, 40, 50]), list([60, 70, 80, 90, 100])], dtype=object)

In [46]:
x=np.array([6,4,7,9])
x.astype('float64')

array([6., 4., 7., 9.])

In [48]:
x=np.array([10,20,40,50])
x.astype('int32')

array([10, 20, 40, 50])

### COPY ARRAY

In [49]:
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=3445
print(a,x)

[3445    2    3    4    5] [1 2 3 4 5]


In [50]:
arr = np.array([1, 2, 3, 4])

print(arr%2)

[1 0 1 0]


In [52]:
a=np.array([1,2,3,4,5])
x=a.copy()
y=a.view()
z=a
a[0]=3445
print(x.base)
print(y.base)
print(z.base)
print(a.base)

None
[3445    2    3    4    5]
None
None


In [54]:
import numpy as np
x=np.array([1,2,3,4,5],ndmin=6)
print(x)
print(x.shape)
print(x.ndim)

[[[[[[1 2 3 4 5]]]]]]
(1, 1, 1, 1, 1, 5)
6


In [55]:
x=np.arange(12)
x1=x.reshape(4,3)
print(x1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [56]:
x2=x1.reshape(2,3,-1)
print(x2)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [57]:
print(x2.reshape(-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [58]:
print(x1)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [59]:
if 8 in x1.reshape(-1):
    print("8 is present in np array")

8 is present in np array


In [60]:
for i in np.nditer(x):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [61]:
for i in x1.reshape(-1):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [62]:
np.random.rand(10)

array([0.44090353, 0.28558721, 0.95301991, 0.20563494, 0.9843643 ,
       0.45263865, 0.80104115, 0.50613072, 0.16860368, 0.42359956])

In [64]:
np.random.rand(5,4)

array([[9.72435118e-01, 7.65373323e-01, 5.60164943e-01, 6.56145589e-01],
       [8.44067083e-01, 3.01699185e-01, 5.23321986e-01, 5.46818479e-01],
       [6.51714812e-01, 3.62161167e-01, 5.91865402e-01, 1.06123090e-01],
       [7.02339846e-02, 8.56051973e-03, 5.72529571e-01, 1.61878580e-04],
       [4.79038703e-01, 9.04459563e-01, 7.60265372e-01, 1.92508135e-01]])

In [67]:
from numpy import random as rd
for i in range(5):
    print(rd.randint(5))

3
0
3
4
0


In [68]:
rd.randint(1,25,(5,8))

array([[22,  5, 15, 14,  2, 19,  8, 15],
       [ 3, 11,  9,  3, 11, 23,  2,  9],
       [12, 24, 16,  7,  5,  5,  4, 22],
       [16, 16,  9, 13,  6, 19, 19, 19],
       [10, 23, 13, 17, 16, 16, 22, 15]])

In [69]:
rd.randint(15,66)

50

In [70]:
rd.randint(15,size=5)

array([ 2,  7,  7,  4, 11])

In [71]:
x=rd.randint(1,45,20).reshape(2,5,2)

In [72]:
x

array([[[ 3, 30],
        [10,  9],
        [13, 35],
        [15, 30],
        [ 8,  4]],

       [[ 3, 26],
        [10, 35],
        [29, 38],
        [20, 39],
        [ 9, 21]]])

In [73]:
x.T

array([[[ 3,  3],
        [10, 10],
        [13, 29],
        [15, 20],
        [ 8,  9]],

       [[30, 26],
        [ 9, 35],
        [35, 38],
        [30, 39],
        [ 4, 21]]])

In [74]:
y=np.random.rand(5,4)
print(y)
print(y.T)

[[0.49285605 0.21296349 0.14463915 0.74470679]
 [0.44209566 0.25674997 0.75371477 0.2505793 ]
 [0.90004554 0.82509529 0.73376872 0.33181533]
 [0.9800719  0.01553896 0.98248533 0.39016999]
 [0.61234672 0.50923652 0.29808926 0.23467155]]
[[0.49285605 0.44209566 0.90004554 0.9800719  0.61234672]
 [0.21296349 0.25674997 0.82509529 0.01553896 0.50923652]
 [0.14463915 0.75371477 0.73376872 0.98248533 0.29808926]
 [0.74470679 0.2505793  0.33181533 0.39016999 0.23467155]]


In [75]:
x=np.eye(3)*4
print(x)

[[4. 0. 0.]
 [0. 4. 0.]
 [0. 0. 4.]]


In [76]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)


(array([3, 5, 6], dtype=int64),)


In [77]:
x=np.eye(5)*4
y=np.where(x==4)
y

(array([0, 1, 2, 3, 4], dtype=int64), array([0, 1, 2, 3, 4], dtype=int64))

In [78]:
x=np.array([[2,3,4,5],[4,2,4,6],[2,4,6,2],[5,4,6,2]],dtype="i8")
y=np.where(x==2)
print(x)
print(y)

[[2 3 4 5]
 [4 2 4 6]
 [2 4 6 2]
 [5 4 6 2]]
(array([0, 1, 2, 2, 3], dtype=int64), array([0, 1, 0, 3, 3], dtype=int64))


In [79]:
def isPrime(n) :
    if (n <= 1) :
        return False
    if(n==2 or n==3):
        return True
    else:
        x=n**(0.5)
        for i in range(2,x):
            if(n%i==0):
                return False
    return True

# This code is contributed
# by Nikita Tiwari.
arr=np.array([[2,3,4,5],[4,2,4,6],[2,4,6,2],[5,4,6,2]],dtype="i8")
y=(isPrime(np.all(arr)))
print(y)

False


In [80]:
x=np.array([3,5,7,3,6])
y=np.array([True,False,True,False,True])
x[y]

array([3, 7, 6])

In [81]:
np.array_split(np.arange(12),4)

[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [82]:
x=np.array([23,5,3])
y=np.array([3,5,3])
np.concatenate((x,y),axis=0)

array([23,  5,  3,  3,  5,  3])

In [83]:
x=np.array([4,7,4])
np.repeat(x,3)

array([4, 4, 4, 7, 7, 7, 4, 4, 4])

In [84]:
a=np.array([2,5,7,83,7])
b=np.array([37,93,9,2,5,7])
np.intersect1d(a,b)

array([2, 5, 7])

In [85]:
x = np.full((4,3),7, dtype = int) 
x

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

In [86]:
x = np.identity(5)     # identity != eye
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [87]:
x=x*4
np.sqrt(x)

array([[2., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 2., 0., 0.],
       [0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 2.]])

In [88]:
x = np.empty([3,2], dtype = int) 
x

array([[ 2,  5],
       [ 7,  9],
       [37, 93]])

In [89]:
x = np.empty([3,2], dtype = int) 
x

array([[ 2,  5],
       [ 7,  9],
       [37, 93]])

In [90]:
x = np.empty([3,2], dtype = int) 
x

array([[ 71761946,         0],
       [        0,         0],
       [        1, 980316009]])

In [91]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [92]:
x = np.zeros(5,dtype=int)
x

array([0, 0, 0, 0, 0])

In [93]:
x = np.zeros(5,dtype=int,order='F')
x

array([0, 0, 0, 0, 0])

In [95]:
list = range(5)
print(list)
it = iter(list)
print(it)

range(0, 5)


In [96]:
x=np.arange(6).reshape(2,3)
for i in (x.reshape(-1)):
    print(i)

0
1
2
3
4
5


In [97]:
x = np.linspace(10,20,5) 
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [98]:
x = np.linspace(10,20) 
x

array([10.        , 10.20408163, 10.40816327, 10.6122449 , 10.81632653,
       11.02040816, 11.2244898 , 11.42857143, 11.63265306, 11.83673469,
       12.04081633, 12.24489796, 12.44897959, 12.65306122, 12.85714286,
       13.06122449, 13.26530612, 13.46938776, 13.67346939, 13.87755102,
       14.08163265, 14.28571429, 14.48979592, 14.69387755, 14.89795918,
       15.10204082, 15.30612245, 15.51020408, 15.71428571, 15.91836735,
       16.12244898, 16.32653061, 16.53061224, 16.73469388, 16.93877551,
       17.14285714, 17.34693878, 17.55102041, 17.75510204, 17.95918367,
       18.16326531, 18.36734694, 18.57142857, 18.7755102 , 18.97959184,
       19.18367347, 19.3877551 , 19.59183673, 19.79591837, 20.        ])

In [99]:
x = np.linspace(10,20, 5, endpoint = False) 
print (x)

[10. 12. 14. 16. 18.]


In [100]:
x = np.linspace(1,2,5, retstep = True) 
print (x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


In [101]:
# default base is 10 
a = np.logspace(1.0, 2.0, num = 10) 
print (a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [102]:
import numpy as np 
a = np.logspace(1,10,num = 10, base = 2) 
print (a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]


In [103]:
import numpy as np 
a = np.logspace(1,5,num = 10, base = 2) 
a

array([ 2.        ,  2.72158   ,  3.70349885,  5.0396842 ,  6.85795186,
        9.33223232, 12.69920842, 17.28095582, 23.51575188, 32.        ])

In [104]:
import numpy as np 
a = np.logspace(0,5,num = 10, base = 2) 
print (a)

[ 1.          1.46973449  2.16011948  3.1748021   4.66611616  6.85795186
 10.0793684  14.8139954  21.77264    32.        ]


In [105]:
x = np.array([[1, 2], [3, 4], [5, 6]]) 
y = x[[0,1,2], [0,1,0]] 
print (y)

[1 4 5]


In [106]:
a = np.array([np.nan, 1,2,np.nan,3,4,5]) 
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [107]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])
a+b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [108]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])
a*b

array([[ 0.,  0.,  0.],
       [10., 20., 30.],
       [20., 40., 60.],
       [30., 60., 90.]])

In [109]:
a = np.arange(0,60,5).reshape(4,-1)
b=a.copy(order = 'C')
for i in np.nditer(b):
    print(i,end=" ")
print()
for j in (b.reshape(-1)):
    print(j,end=" ")
print("\n\n")
c=a.copy(order = 'F')
for i in np.nditer(c):
    print(i,end=" ")
print()
for j in (c.reshape(-1)):
    print(j,end=" ")

0 5 10 15 20 25 30 35 40 45 50 55 
0 5 10 15 20 25 30 35 40 45 50 55 


0 15 30 45 5 20 35 50 10 25 40 55 
0 5 10 15 20 25 30 35 40 45 50 55 

In [110]:
print(a)
a=a*2
print(a)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]]
[[  0  10  20]
 [ 30  40  50]
 [ 60  70  80]
 [ 90 100 110]]


In [111]:
a = np.arange(4,12).reshape(2,4) 
print ('The original array:' ) 
print (a)

print ('After applying the flat function:') 
# returns element corresponding to index in flattened array 
a.flat[5]

The original array:
[[ 4  5  6  7]
 [ 8  9 10 11]]
After applying the flat function:


9

In [112]:
a = np.arange(4,12).reshape(2,4) 
print ('The flattened array is:') 
print (a.flatten() )

print ('The flattened array in F-style ordering:' )
print (a.flatten(order = 'F'))

The flattened array is:
[ 4  5  6  7  8  9 10 11]
The flattened array in F-style ordering:
[ 4  8  5  9  6 10  7 11]


In [113]:
print ('After applying ravel function:' )
print (a.ravel()  )
print ('\n' )

print ('Applying ravel function in F-style ordering:' )
print (a.ravel(order = 'F'))

After applying ravel function:
[ 4  5  6  7  8  9 10 11]


Applying ravel function in F-style ordering:
[ 4  8  5  9  6 10  7 11]


In [114]:
 np.bitwise_and(13, 1)

1

## Arithmetic Operation using numpy

In [2]:
import numpy as np
x=np.array([1,2,3,4,5,6,7])
x

array([1, 2, 3, 4, 5, 6, 7])

In [3]:
x%2

array([1, 0, 1, 0, 1, 0, 1], dtype=int32)

In [4]:
x/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5])

In [5]:
x**2

array([ 1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [6]:
np.sin(x)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ])

In [8]:
np.tan(x[1:2])

array([-2.18503986])

### Linear Algebra

In [10]:
a=np.array([[1,2,3,4],[56,7,9,3]])
b=np.array([[2,5],[58,7],[68,5],[4,8]])
print(a)
print(b)

np.matmul(a,b)

[[ 1  2  3  4]
 [56  7  9  3]]
[[ 2  5]
 [58  7]
 [68  5]
 [ 4  8]]


array([[ 338,   66],
       [1142,  398]])

In [11]:
x=np.matmul(a,b)
np.linalg.det(x)

59151.999999999956

In [12]:
np.linalg.eig(x)

(array([ 91.82614172, 644.17385828]),
 array([[-0.25895784, -0.21072347],
        [ 0.96588863, -0.97754571]]))

### Statistics

In [13]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.min(x)

1

In [15]:
np.min(x,axis=1)

array([1, 4, 7])

In [16]:
np.min(x,axis=0)

array([1, 2, 3])

In [17]:
np.max(x)

9

In [18]:
np.max(x,axis=1)

array([3, 6, 9])

In [19]:
np.sum(x)

45

In [20]:
np.sum(x,axis=0)

array([12, 15, 18])

In [21]:
np.mean(x)

5.0

In [22]:
np.median(x)

5.0

In [23]:
np.std(x)

2.581988897471611

In [24]:
np.var(x)

6.666666666666667

### linear Equation

#### 4 x + 5 y = 13
#### 5 x - 3 y = 7

In [25]:
mat1=np.array([[4,5],[5,-3]])
mat2=np.array([13,7])

np.linalg.solve(mat1,mat2)

array([2., 1.])