In [1]:
import numpy as np

In [2]:
#Question 1

arr1=np.array([0,10,20,40,60,80])
arr2=np.array([10,30,40,50,70])
x=np.union1d(arr1,arr2)
x

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80])

In [3]:
#Question 2

x=np.array([4,8,7])
y=np.array([6,5,7])
print(x>y)
print(x<y)
print(x<=y)
print(x>=y)

[False  True False]
[ True False False]
[ True False  True]
[False  True  True]


In [4]:
#Question 3

x=np.arange(1,7).reshape(2,3)
print(x)
print(x.shape)
print(x.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int32


In [5]:
#Question 4

x=np.zeros([3,5])
y=np.ones([3,5])*12
print(x)
print()
print(y)


[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]
 [12. 12. 12. 12. 12.]]


In [6]:
#Question 5

y=int(input())
x=np.arange(1,11)
print(x*y)

7
[ 7 14 21 28 35 42 49 56 63 70]


In [7]:
#Quetion 6
arr=np.array([58,4,7,9,4,-3,5,2,-4])
print("Mergesort = ", np.sort(arr, -1, 'mergesort'))
print("Quicksort = ", np.sort(arr, -1, 'quicksort'))

Mergesort =  [-4 -3  2  4  4  5  7  9 58]
Quicksort =  [-4 -3  2  4  4  5  7  9 58]


In [8]:
#Question 7

x=np.array([[3,5,8],[4,9,3],[6,3,8]])
y=np.array([[8,5,3],[4,7,2],[5,3,2]])
print("addition  :\n",x+y)
print("\nsubtract: \n", x-y)



addition  :
 [[11 10 11]
 [ 8 16  5]
 [11  6 10]]

subtract: 
 [[-5  0  5]
 [ 0  2  1]
 [ 1  0  6]]


In [9]:
#Question 8

def enqueue(l,x):
    l = np.append(l, x)
    return l


def dequeue(l):
    if(len(l)>0):
        l=np.delete(l,0)
    return l

def isempty(l):
    if(len(l)>0):
        return False
    else:
        return True


        
l=np.array([3,7,9,-6,3])
print(l)
l=enqueue(l,6)
l=dequeue(l)
print(isempty(l))
print(l)

[ 3  7  9 -6  3]
False
[ 7  9 -6  3  6]
