# Assignment on NumPy

Name     : Vaibhav Bichave

Roll No. : 33209



In [1]:
import numpy as np

In [2]:
#1. Write a NumPy program to get the NumPy version and show NumPy build configuration. 

print(np.__version__)
print(np.show_config())

1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Admin/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/Admin/anaconda3\\Library\\include']
None


In [3]:
#2. Write a NumPy program to get help on the add function. 

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [4]:
#3. Write a NumPy program to test whether none of the elements of a given array is zero. 

x = np.array([4,36,8,3])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))
x = np.array([5,8,0,23])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))


Original array:
[ 4 36  8  3]
Test if none of the elements of the said array is zero:
True
Original array:
[ 5  8  0 23]
Test if none of the elements of the said array is zero:
False


In [5]:
#4. Write a NumPy program to test whether any of the elements of a given array is nonzero. 

x = np.array([0,0,56,0,0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))
x = np.array([0, 0, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))

Original array:
[ 0  0 56  0  0]
Test whether any of the elements of a given array is non-zero:
True
Original array:
[0 0 0 0 0]
Test whether any of the elements of a given array is non-zero:
False


In [6]:
#5. Write a NumPy program to test a given array elementwise for finiteness (not infinity or not a Number). 

a = np.array([0, np.nan, -46, 57, np.inf])
print("Original array")
print(a)
print("Test a given array element-wise for finiteness :")
print(np.isfinite(a))

Original array
[  0.  nan -46.  57.  inf]
Test a given array element-wise for finiteness :
[ True False  True  True False]


In [7]:
#6. Write a NumPy program to test elementwise for positive or negative infinity.

a = np.array([0, np.nan, -46, 57, np.inf])
print("Original array")
print(a)
print("Test element-wise for positive or negative infinity:")
print(np.isinf(a))

Original array
[  0.  nan -46.  57.  inf]
Test element-wise for positive or negative infinity:
[False False False False  True]


In [8]:
#7. Write a NumPy program to test elementwise for NaN (Not a Number) of a given array. 

a = np.array([0, np.nan, -46, 57, np.inf])
print("Original array")
print(a)
print("Test element-wise for NaN:")
print(np.isnan(a))

Original array
[  0.  nan -46.  57.  inf]
Test element-wise for NaN:
[False  True False False False]


In [9]:
#8. Write a NumPy program to test elementwise for complex number, real number of a
#   given array. Also test whether a given number is a scalar type or not. 

a = np.array([4+1j, 1+2j, 85.5, -4, 24, 65j])
print("Original array")
print(a)
print("Checking for complex number:")
print(np.iscomplex(a))
print("Checking for real number:")
print(np.isreal(a))
print()
print("Checking for scalar type:")
print(np.isscalar(3.1))
print(np.isscalar(a))

Original array
[ 4.  +1.j  1.  +2.j 85.5 +0.j -4.  +0.j 24.  +0.j  0. +65.j]
Checking for complex number:
[ True  True False False False  True]
Checking for real number:
[False False  True  True  True False]

Checking for scalar type:
True
False


In [10]:
#9. Write a NumPy program to test whether two arrays are element-wise equal within a tolerance 

print("Test if two arrays are element-wise equal within a tolerance:")
print(np.allclose([1e10,1e-7], [1.00001e10,1e-8]))
print(np.allclose([1e10,1e-8], [1.00001e10,1e-9]))
print(np.allclose([1e10,1e-8], [1.0001e10,1e-9]))
print(np.allclose([1.0, np.nan], [1.0, np.nan]))
print(np.allclose([1.0, np.nan], [1.0, np.nan], equal_nan=True))

Test if two arrays are element-wise equal within a tolerance:
False
True
False
False
True


In [11]:
# 10. Write a NumPy program to create an element-wise comparison (greater, greater
#     equal, less and less equal) of two given arrays 

x = np.array([3,-6,8])
y = np.array([3,7,0])
print("Original numbers:")
print(x)
print(y)
print("Comparison - greater")
print(np.greater(x, y))
print("Comparison - greater_equal")
print(np.greater_equal(x, y))
print("Comparison - less")
print(np.less(x, y))
print("Comparison - less_equal")
print(np.less_equal(x, y))

Original numbers:
[ 3 -6  8]
[3 7 0]
Comparison - greater
[False False  True]
Comparison - greater_equal
[ True False  True]
Comparison - less
[False  True False]
Comparison - less_equal
[ True  True False]


In [12]:
#11. Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays. 

x = np.array([72, 79, 85, 90, 67, -135, -10, 60, 10])
y = np.array([72, 79, 85, 90, 67, -135, -10, 60, 10.01])
print("Original numbers:")
print("x : ",x)
print("y : ",y)
print("Comparison - equal:")
print(np.equal(x, y))
print("Comparison - equal within a tolerance:")
print(np.allclose(x, y))

Original numbers:
x :  [  72   79   85   90   67 -135  -10   60   10]
y :  [  72.     79.     85.     90.     67.   -135.    -10.     60.     10.01]
Comparison - equal:
[ True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:
False


In [13]:
#12. Write a NumPy program to create an array with the values 1, 7, 13, 105 and
#    determine the size of the memory occupied by the array 

X = np.array([64,8,0,-64])
print("Original array:")
print(X)
print("Size of the memory occupied by the said array:")
print("%d bytes" % (X.size * X.itemsize))

Original array:
[ 64   8   0 -64]
Size of the memory occupied by the said array:
16 bytes


In [14]:
#13. Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives. 

array=np.zeros(10)
print("An array of 10 zeros:")
print(array)
array=np.ones(10)
print("An array of 10 ones:")
print(array)
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [15]:
#14. Write a NumPy program to create an array of the integers from 30 to70

array=np.arange(30,71)
print("Array of the integers from 30 to70")
print(array)

Array of the integers from 30 to70
[30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [16]:
#15. Write a NumPy program to create an array of all the even integers from 30 to 70.

array=np.arange(30,71,2)
print("Array of all the even integers from 30 to 70")
print(array) 


Array of all the even integers from 30 to 70
[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


In [17]:
#16. Write a NumPy program to create a 3x3 identity matrix. 

array_2D=np.identity(3)
print('3x3 matrix:')
print(array_2D)

3x3 matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
#17. Write a NumPy program to generate a random number between 0 and 1.

rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[1.49320725]


In [19]:
#18. Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution 

rand_num = np.random.normal(0,1,15)
print("15 random numbers from a standard normal distribution:")
print(rand_num)

15 random numbers from a standard normal distribution:
[ 0.07656814  0.93598985 -0.46110852  0.1807607  -1.45629867 -0.09653926
 -0.0145322  -0.46055411  1.84633718  0.50073293  0.89101354 -0.72419166
 -0.61990742 -0.14238214 -0.01097973]


In [20]:
#19. NumPy program to create a vector with values ranging from 15 to 55 and 
#    print all values except the first and last

v = np.arange(15,55)
print("Original vector:")
print(v)
print("All values except the first and last of the said vector:")
print(v[1:-1])

Original vector:
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54]
All values except the first and last of the said vector:
[16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39
 40 41 42 43 44 45 46 47 48 49 50 51 52 53]


In [21]:
#20. Write a NumPy program to create a 3X4 array using and iterate over it

a = np.arange(12).reshape((3, 4))
print("Original array:")
print(a)
print("Each element of the array is:")
for x in np.nditer(a):
  print(x,end=" ")

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Each element of the array is:
0 1 2 3 4 5 6 7 8 9 10 11 

In [22]:
#21. Write a NumPy program to create a vector of length 10 with values evenly 
#    distributed between 5 and 50. 

v = np.linspace(5, 50, 10)
print("Length 10 with values evenly distributed between 5 and 50:")
print(v)

Length 10 with values evenly distributed between 5 and 50:
[ 5. 10. 15. 20. 25. 30. 35. 40. 45. 50.]


In [23]:
# 22. Write a NumPy program to create a vector with values from 0 to 20 and change the
#     sign of the numbers in the range from 9 to 15 

x = np.arange(21)
print("Original vector:")
print(x)
print("After changing the sign of the numbers in the range from 9 to 15:")
x[(x >= 9) & (x <= 15)] *= -1
print(x)


Original vector:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
After changing the sign of the numbers in the range from 9 to 15:
[  0   1   2   3   4   5   6   7   8  -9 -10 -11 -12 -13 -14 -15  16  17
  18  19  20]


In [24]:
#23. Write a NumPy program to create a vector of length 5 filled with arbitrary integers from 0 to 10. 

x = np.random.randint(0, 11, 5)
print("Vector of length 5 filled with arbitrary integers from 0 to 10:")
print(x)

Vector of length 5 filled with arbitrary integers from 0 to 10:
[3 8 8 5 8]


In [25]:
#24. Write a NumPy program to multiply the values of two given vectors

x = np.array([4,7,9,-3])
print("Vector-1")
print(x)
y= np.random.randint(0, 11, 4)
print("Vector-2")
print(y)
result = x * y
print("Multiply the values of two said vectors:")
print(result)

Vector-1
[ 4  7  9 -3]
Vector-2
[3 2 7 8]
Multiply the values of two said vectors:
[ 12  14  63 -24]
